### PR TITLE
Replace lost puppetdoc for home_dir_perms

### PR DESCRIPTION
**Pull request by rjw1**
The documentation for this variable was lost in e15b4e3c93

### CODE REVIEW

**Comment by torrancew** [comment]
@rjw1 This feature is actually being deprecated, but I didn't want to break functionality just yet (I believe that was my intent, anyway -- you can see that `$home_dir_perms` param is no longer passed through). Would that represent a problem for you?

**Comment by rjw1** [comment]
I do actually [use](https://github.com/rjw1/randomness-puppet/blob/master/hieradata/common.yaml#L31) `home_dir_perms`.
I hadn't realised that the behaviour had changed in that commit as well.
To be honest a breaking change would have been better than an option that does nothing or at least a warning message if its set to something other than the default.
I actually pin to a commit in my [Puppetfile](https://github.com/rjw1/randomness-puppet/blob/master/Puppetfile#L11) anyway so probably wouldn't notice.

**Comment by torrancew** [comment]
Ok, I'll reverse course on that then, and restore functionality to that flag!

**Comment by rjw1** [comment]
Thanks :+1:

**Comment by torrancew** [comment]
@rjw1 Opened #54 to track the regression. I'm going to close this out, as there's more work to be done here than just restoring the docstring. Should have this resolved in a day or two.

**Comment by torrancew** [comment]
Hmmm, I seem to have been on the wrong branch, docs seem to be the only missing piece here.

**Pull request merged**
