### PR TITLE
Add support for multiple ssh_authorized_keys

### PR DESCRIPTION
**Pull request by torrancew**
This adds support for multiple SSH authorized_key entries for an account via a new ```ssh_keys``` parameter, deprecating the old ```ssh_key``` and ```ssh_key_type``` parameters.

It implements roughly the same functionality as #7, but in a different way.

### CODE REVIEW

**Comment by elisiano** [comment]
@torrancew was there any progress on this? Can you explain the issue with the create_resources and the virtual/exported resources?

**Comment by torrancew** [comment]
@elisiano the issue around exported/virtual users is a bit murky.

Assume that we have an account resource that is virtual: `@account { 'foo': }`
If we try to use create_resources as the avenue to create multiple ssh keys, those keys need to have the same state as the account resource itself - if account is virtual/exported, the ssh key must be, too.
To do this, we need to modify the call to create_resources, so that if Account[$title] is virutal, we need to prefix '@' to the resource type in the create_resources call. I did some initial testing around this, but was not very successful. This is further complicated by the fact that users (and in theory, this type as well) are a prime use case for virtual resources in many environments.

**Comment by elisiano** [comment]
@torrancew, thanks for getting back, I've been playing with this myself (I've actually merged this branch with the master and deployed in production).
I would expect the behavior as you described it as well but to my surprise the keys don't get created if the virtual user is not realized (hence everything work as it should by default, with no further modifications).
Now, this is only with virtual resources, I don't know how this behaves in case of exported resources but, as you pointed out, the user pattern usually use virtual resources.

I've also added the possibility to have multiple private keys (which is basically just 'file' resources) and it behaves exactly as the ssh_authorized_keys: they get created only when the user is realized.

The code is not public for the moment but if there's interest I can share it.

**Comment by torrancew** [comment]
In the **long** time that has passed since this was opened, the "future parser" is now the current parser. I'm going to sit down and write this utilizing Puppet 4 functionality, and cut a new major release for that. #43 will track that.

**Pull request closed without merging**
